<?php

return [
    'list' => [
        // ============================
        // TIER 1: arXiv (rich Atom)
        // ============================
        [
            'key'         => 'arxiv_math_all',
            'label'       => 'arXiv — Mathematics (all)',
            'kind'        => 'primary',
            'disciplines' => ['math'],
            'url'         => 'http://export.arxiv.org/api/query?search_query=cat:math.*&sortBy=submittedDate&sortOrder=descending&max_results=25',
            'signal'      => 'latest preprints',
            'notes'       => 'Open, structured, abstracts available (Cornell).',
        ],

        // --- Popular subfields (arXiv categories) ---
        [
            'key' => 'arxiv_math_AG',
            'label' => 'arXiv — Algebraic Geometry (math.AG)',
            'kind' => 'primary',
            'disciplines' => ['math'],
            'url' => 'http://export.arxiv.org/api/query?search_query=cat:math.AG&sortBy=submittedDate&sortOrder=descending&max_results=15',
            'signal' => 'latest preprints',
            'notes' => 'Subfield feed.',
        ],
        [
            'key' => 'arxiv_math_AT',
            'label' => 'arXiv — Algebraic Topology (math.AT)',
            'kind' => 'primary',
            'disciplines' => ['math'],
            'url' => 'http://export.arxiv.org/api/query?search_query=cat:math.AT&sortBy=submittedDate&sortOrder=descending&max_results=15',
            'signal' => 'latest preprints',
            'notes' => 'Subfield feed.',
        ],
        [
            'key' => 'arxiv_math_CO',
            'label' => 'arXiv — Combinatorics (math.CO)',
            'kind' => 'primary',
            'disciplines' => ['math'],
            'url' => 'http://export.arxiv.org/api/query?search_query=cat:math.CO&sortBy=submittedDate&sortOrder=descending&max_results=15',
            'signal' => 'latest preprints',
            'notes' => 'Subfield feed.',
        ],
        [
            'key' => 'arxiv_math_DG',
            'label' => 'arXiv — Differential Geometry (math.DG)',
            'kind' => 'primary',
            'disciplines' => ['math'],
            'url' => 'http://export.arxiv.org/api/query?search_query=cat:math.DG&sortBy=submittedDate&sortOrder=descending&max_results=15',
            'signal' => 'latest preprints',
            'notes' => 'Subfield feed.',
        ],
        [
            'key' => 'arxiv_math_FA',
            'label' => 'arXiv — Functional Analysis (math.FA)',
            'kind' => 'primary',
            'disciplines' => ['math'],
            'url' => 'http://export.arxiv.org/api/query?search_query=cat:math.FA&sortBy=submittedDate&sortOrder=descending&max_results=15',
            'signal' => 'latest preprints',
            'notes' => 'Subfield feed.',
        ],
        [
            'key' => 'arxiv_math_GT',
            'label' => 'arXiv — Geometric Topology (math.GT)',
            'kind' => 'primary',
            'disciplines' => ['math'],
            'url' => 'http://export.arxiv.org/api/query?search_query=cat:math.GT&sortBy=submittedDate&sortOrder=descending&max_results=15',
            'signal' => 'latest preprints',
            'notes' => 'Subfield feed.',
        ],
        [
            'key' => 'arxiv_math_NT',
            'label' => 'arXiv — Number Theory (math.NT)',
            'kind' => 'primary',
            'disciplines' => ['math'],
            'url' => 'http://export.arxiv.org/api/query?search_query=cat:math.NT&sortBy=submittedDate&sortOrder=descending&max_results=15',
            'signal' => 'latest preprints',
            'notes' => 'Subfield feed.',
        ],
        [
            'key' => 'arxiv_math_PR',
            'label' => 'arXiv — Probability (math.PR)',
            'kind' => 'primary',
            'disciplines' => ['math'],
            'url' => 'http://export.arxiv.org/api/query?search_query=cat:math.PR&sortBy=submittedDate&sortOrder=descending&max_results=15',
            'signal' => 'latest preprints',
            'notes' => 'Subfield feed.',
        ],
        [
            'key' => 'arxiv_math_RA',
            'label' => 'arXiv — Rings and Algebras (math.RA)',
            'kind' => 'primary',
            'disciplines' => ['math'],
            'url' => 'http://export.arxiv.org/api/query?search_query=cat:math.RA&sortBy=submittedDate&sortOrder=descending&max_results=15',
            'signal' => 'latest preprints',
            'notes' => 'Subfield feed.',
        ],
        [
            'key' => 'arxiv_math_RT',
            'label' => 'arXiv — Representation Theory (math.RT)',
            'kind' => 'primary',
            'disciplines' => ['math'],
            'url' => 'http://export.arxiv.org/api/query?search_query=cat:math.RT&sortBy=submittedDate&sortOrder=descending&max_results=15',
            'signal' => 'latest preprints',
            'notes' => 'Subfield feed.',
        ],
        [
            'key' => 'arxiv_math_OC',
            'label' => 'arXiv — Optimization and Control (math.OC)',
            'kind' => 'primary',
            'disciplines' => ['math'],
            'url' => 'http://export.arxiv.org/api/query?search_query=cat:math.OC&sortBy=submittedDate&sortOrder=descending&max_results=15',
            'signal' => 'latest preprints',
            'notes' => 'Subfield feed.',
        ],
        [
            'key' => 'arxiv_math_NA',
            'label' => 'arXiv — Numerical Analysis (math.NA)',
            'kind' => 'primary',
            'disciplines' => ['math'],
            'url' => 'http://export.arxiv.org/api/query?search_query=cat:math.NA&sortBy=submittedDate&sortOrder=descending&max_results=15',
            'signal' => 'latest preprints',
            'notes' => 'Subfield feed.',
        ],
        [
            'key' => 'arxiv_math_AP',
            'label' => 'arXiv — Analysis of PDEs (math.AP)',
            'kind' => 'primary',
            'disciplines' => ['math'],
            'url' => 'http://export.arxiv.org/api/query?search_query=cat:math.AP&sortBy=submittedDate&sortOrder=descending&max_results=15',
            'signal' => 'latest preprints',
            'notes' => 'Subfield feed.',
        ],
        [
            'key' => 'arxiv_math_ST',
            'label' => 'arXiv — Statistics Theory (math.ST)',
            'kind' => 'primary',
            'disciplines' => ['math'],
            'url' => 'http://export.arxiv.org/api/query?search_query=cat:math.ST&sortBy=submittedDate&sortOrder=descending&max_results=15',
            'signal' => 'latest preprints',
            'notes' => 'Subfield feed.',
        ],

        // ============================
        // TIER 1b: bioRxiv / medRxiv (JSON)
        // ============================
        [
            'key'         => 'biorxiv_recent',
            'label'       => 'bioRxiv — Recent (quant/math adjacent)',
            'kind'        => 'json',
            'disciplines' => ['math'],
            'url'         => 'https://api.biorxiv.org/details/biorxiv/50',
            'signal'      => 'latest preprints',
            'notes'       => 'Structured JSON (title/abstract/DOI).',
        ],
        [
            'key'         => 'medrxiv_recent',
            'label'       => 'medRxiv — Recent (methods/stats)',
            'kind'        => 'json',
            'disciplines' => ['math'],
            'url'         => 'https://api.medrxiv.org/details/medrxiv/50',
            'signal'      => 'latest preprints',
            'notes'       => 'Structured JSON (title/abstract/DOI).',
        ],
    ],
];
